stages:
  data_ingetion:
    cmd: python  ./src/data/data_ingetion.py
    deps:
    - ./src/data/data_ingetion.py
    params:
    - data_ingetion.test_size
    - data_ingetion.random_state
    outs:
    - ./data/raw/train.csv
    - ./data/raw/test.csv

  feature_eg:
    cmd: python ./src/features/feature_eg.py
    deps:
    - ./src/features/feature_eg.py
    - ./data/raw/train.csv
    - ./data/raw/test.csv
    params:
    - feature_eg.n_components
    outs:
    - ./data/processed/train_processed.csv
    - ./data/processed/test_processed.csv

  train_model:
    cmd: python ./src/models/train_model.py
    deps:
    - ./src/models/train_model.py
    - ./data/processed/train_processed.csv
    params:
    - train_model.n_estimators
    - train_model.max_depth
    - train_model.bootstrap
    - train_model.criterion
    outs:
    - ./models/model.joblib
    # - dvclive/metrics.json

  # predict_model:
  #   cmd: python ./src/models/predict_model.py
  #   deps:
  #   - ./src/models/predict_model.py
  #   - ./models/model.joblib
  #   - ./data/processed/test_processed.csv
  #   params:
  #   - data_ingetion.test_size
  #   - data_ingetion.random_state
  #   - feature_eg.n_components
  #   - train_model.n_estimators
  #   - train_model.max_depth
  #   - train_model.bootstrap
  #   - train_model.criterion
  #   outs:
  #   - dvclive/metrics.json

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
